---
- hosts: webservers
  become: yes
  tasks:
  - name: Update and upgrade apt packages
    apt:
      upgrade: yes
      update_cache: yes
      cache_valid_time: 86400 #One day
  - name: "Install Java"
    apt:
      name: openjdk-8-jdk
      state: present
  - name: "Download tomcat server packages"
    get_url:
      url: https://mirror.olnevhost.net/pub/apache/tomcat/tomcat-8/v8.5.63/bin/apache-tomcat-8.5.63.tar.gz
      dest: /usr/local
  - name: "extract tomcat packages"
    unarchive: 
      src: /usr/local/apache-tomcat-8.5.63.tar.gz
      dest: /usr/local
      remote_src: yes
  - name: "start tomcat service"
    shell: nohup /usr/local/apache-tomcat-8.5.63/bin/startup.sh
- hosts: node1
  become: yes
  tasks:
  - name: Update and upgrade apt packages
    apt:
      upgrade: yes
      update_cache: yes
      cache_valid_time: 86400 #One day
  - name: "Install Java"
    apt:
      name: openjdk-8-jdk
      state: present
  - name: "Install Jenkins on Node1"
    apt_key: url=https://pkg.jenkins.io/debian-stable/jenkins.io.key state=present
  - name: ensure the repository is configured
    apt_repository: repo='deb https://pkg.jenkins.io/debian-stable binary/' state=present
  - name: "Check Jenkins is installed"
    apt: name=jenkins update_cache=yes
    become: yes
  - name: "Start the Jenkins service"
    service: name=jenkins state=started
  - name: "Pause for 10 seconds"
    pause:
      seconds: 10
  - name: "Get Jenkins initial Admin Password"
    shell: "cat /var/lib/jenkins/secrets/initialAdminPassword"
    changed_when: false
    register: result
  - name: "Echo the password"
    debug:
     var: result.stdout